name: Issue moderator

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Check no title issue
        uses: tachiyomiorg/issue-moderator-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          auto-close-rules: |
            [
              {
                "type": "title",
                "regex": ".*(Short description|简单描述).*",
                "message": "You did not fill out the description in the title/你没有填写标题"
              }
            ]
          auto-close-ignore-label: do-not-autoclose
      - name: Check version issue
        uses: tachiyomiorg/issue-moderator-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          auto-close-rules: |
            [
              {
                "type": "body",
                "regex": ".*(version is too old|version too old|太旧|过旧).*",
                "message": "Upgrade your KernelSU / 升级 KernelSU"
              }
            ]
          auto-close-ignore-label: do-not-autoclose

